# Generated by Django 3.2.8 on 2021-11-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='number_task',
        ),
        migrations.AddField(
            model_name='project',
            name='number_tasks',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Number of Tasks'),
        ),
        migrations.AddField(
            model_name='project',
            name='percent_completed',
            field=models.FloatField(default=0, verbose_name='Percent Completed'),
        ),
    ]
