# Generated by Django 3.2.8 on 2021-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20211102_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='percent_completed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Percent Completed'),
        ),
    ]
