# Generated by Django 3.2.8 on 2021-11-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_percent_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='real_duration',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='project',
            name='str_duration',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='String Duration'),
        ),
    ]
