# Generated by Django 3.2.8 on 2021-10-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SmallIntegerField(blank=True, verbose_name='Code')),
                ('title', models.CharField(max_length=30, verbose_name='Title')),
                ('description', models.CharField(blank=True, max_length=70, null=True, verbose_name='Description')),
                ('status', models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In process'), (2, 'Paused'), (3, 'Finalized'), (4, 'Canceled')], default=0, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Start')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='End')),
                ('real_duration', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Duration')),
                ('estimated_duration', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Estimated Duration')),
                ('times', models.JSONField(blank=True, default=list, null=True, verbose_name='Times')),
            ],
        ),
    ]
