# Generated by Django 3.2.5 on 2021-10-26 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.SmallIntegerField(default=75, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_duration',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Estimated Duration'),
        ),
        migrations.AddField(
            model_name='task',
            name='real_duration',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Duration'),
        ),
        migrations.AddField(
            model_name='task',
            name='times',
            field=models.JSONField(default=list, verbose_name='Times'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In process'), (2, 'Paused'), (3, 'Finalized')], verbose_name='Status'),
        ),
    ]
