# Generated by Django 3.2.8 on 2021-10-30 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='str_duration',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='String Duration'),
        ),
    ]
