# Generated by Django 3.2.5 on 2021-10-26 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20211026_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In process'), (2, 'Paused'), (3, 'Finalized'), (4, 'Eliminated')], verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Title'),
        ),
    ]
