# Generated by Django 3.2.5 on 2021-10-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20211026_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='times',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Times'),
        ),
    ]
