# Generated by Django 3.2.8 on 2021-10-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20211026_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code',
            field=models.SmallIntegerField(blank=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In process'), (2, 'Paused'), (3, 'Finalized'), (4, 'Eliminated')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
    ]
