# Generated by Django 3.2.8 on 2021-10-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20211027_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Pending'), (1, 'In process'), (2, 'Paused'), (3, 'Finalized'), (4, 'Canceled')], default=0, verbose_name='Status'),
        ),
    ]
