# Generated by Django 3.2.5 on 2021-10-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Slug'),
        ),
    ]
